CURRY_TEXT_6k_tokens = """
Professional career

NBA championship and MVP (2014–2015)

Curry about to pass while being guarded by John Wall and Nenê of the Washington Wizards. Curry averaged 7.7 assists per game during the 2014–15 regular season, good enough for sixth-best in the league.[66]
Prior to the start of the 2014–15 season, the Warriors hired former NBA player and general manager Steve Kerr as their new head coach.[67] Kerr implemented significant changes to Golden State's schemes, including playing at a faster pace and giving Curry more freedom to shoot, helping the team evolve into a title contender.[68] On February 4, Curry scored a season-high 51 points in a win over the Dallas Mavericks.[69] He was the leading vote-getter for the All-Star Game and won the Three-Point Contest on All-Star Saturday night.[70][71] On April 9, he broke his own league record for three-pointers made in a season during a game against the Portland Trail Blazers.[72] The Warriors finished the year with 67 wins and Curry was voted the NBA Most Valuable Player after posting averages of 23.8 points, 7.7 assists, and 2 steals per game.[73] Over the course of the season, he sat out 17 fourth quarters due to Golden State's wide margins of victory.[74]

In Game 5 of the Conference Semifinals against the Memphis Grizzlies, Curry became the first player in league history to register 6 three-pointers and six steals in a game.[75] In Game 6, he made a playoff career-high 8 three-pointers en route to a series-clinching victory.[76] In Game 3 of the Conference Finals against the Houston Rockets, he broke the NBA record for most three-pointers made in a single postseason.[77][78] The Warriors went on to defeat the Rockets to earn a Finals matchup with the Cleveland Cavaliers, where Curry struggled to start the series, converting on only 22 percent of his field goals in Game 2.[79] In Game 5, he scored 37 points,[80] and in Game 6, Golden State closed out the series to win their first championship in 40 years.[81] For the Finals, Curry averaged 26 points and 6.3 assists per game.[80] The Warrior's playoff run was the first in which an All-NBA first team selection eliminated all other first team selections in on the way to a championship.[82]

Unanimous MVP and historic season (2015–2016)

To start the 2015–16 season, Curry became the first player since Michael Jordan in 1989–90 to score 118 points in his team's first three games,[83] including a season-high 53 points against the New Orleans Pelicans in the third game.[84] The Warriors made NBA history on November 24 when they became the first team ever to start 16–0 with a win over the Los Angeles Lakers,[85] before improving to 24–0 on December 11 with a double-overtime win over the Boston Celtics.[86] Their streak was broken the following day against the Milwaukee Bucks.[87] On December 28, Curry recorded his sixth career triple-double with 23 points, a career-high 14 rebounds and 10 assists in a 122–103 win over the Sacramento Kings. During the game, Curry was guarded by his brother Seth for the first time in their NBA careers.[88] On January 22, he recorded his second triple-double of the season with 39 points, 12 assists, and 10 rebounds in a 122–110 win over the Indiana Pacers. He made 8 three-pointers in the game to reach 200 for the season, becoming the first player in NBA history to make 200 three-pointers in four straight seasons.[89] On February 3, he made 11 three-pointers (including seven in the first quarter) and scored 51 points (including a career-high 36 points in the first half) to lead the Warriors past the Washington Wizards 134–121. His 51 points tied Gilbert Arenas and Michael Jordan for the Verizon Center record.[90]

During the 2016 NBA All-Star Weekend, Curry competed in his third straight All-Star game for the West, and competed in the Three-Point Contest, where he lost in the final round to teammate Klay Thompson. At 48–4, the Warriors entered the All-Star break with the best record through 52 games in NBA history, one win better than the 1995–96 Chicago Bulls and 1966–67 Philadelphia 76ers.[91]

On February 25, Curry made 10 three-pointers and scored 51 points to lead the Warriors past the Orlando Magic 130–114. Curry topped 50 points for the third time in 2015–16, the first player to do it that many times since LeBron James and Dwyane Wade did so in 2008–09. Curry also surpassed Kyle Korver's mark of 127 straight games with a three-pointer.[92] With only one made free throw, Curry set a record for fewest free throws in a 50+ game.[82] In the following game two days later, the Warriors defeated the Oklahoma City Thunder in overtime thanks to a Curry three-pointer with 0.6 seconds remaining; tying the NBA single-game record with Kobe Bryant and Donyell Marshall, Curry finished with 46 points as his winning shot was his 12th three-pointer.[93] He also broke his own NBA record for threes in a season, leaving the new mark at 288.[94] On March 7, in a win over the Magic, Curry scored 41 points and became the first player in NBA history to make 300 regular-season three-pointers.[95] On April 1, Curry missed a three-pointer to tie the game against the Celtics with 5.3 seconds left, as the Warriors suffered their first home defeat since January 27, 2015, snapping an NBA-record 54-game winning streak in the regular season at Oracle Arena.[96] On April 7, Curry scored 27 points to help the Warriors become the second team in NBA history to win 70 games in a season with a 112–101 win over the San Antonio Spurs.[97] Three days later in a rematch against the Spurs, Stephen Curry scored 37 points in a 92–86 win, not only tying the 1996 Bulls, but snapping San Antonio's undefeated home streak and also ending a long losing streak in AT&T Center.[98]

In the Warriors' regular-season finale on April 13 against the Memphis Grizzlies, Curry achieved another shooting milestone, becoming the first player to make 400 three-pointers in a season by knocking down 10 from long range on his way to 46 points and 402 total three-pointers. With a 125–104 win over the Grizzlies, the Warriors became the first 73-win team in NBA history, surpassing the 1995–96 Chicago Bulls' 72–10 record to finish the 2015–16 season with just nine losses.[99] With the conclusion of the regular season, Curry became the seventh player in NBA history to join the 50–40–90 club, representing the shooting percentages from the field (.504), beyond the arc (.454), and the free-throw line (.908).[100] The league's leading scorer at 30.1 points per game, he posted the highest scoring average of the first 29 50–40–90 seasons.[82] Curry was named the league's first ever unanimous MVP, becoming the 11th player in NBA history to win the award in consecutive seasons and the first guard to do so since Steve Nash in 2004–05 and 2005–06.[101] His scoring average increase of 6.3 is the largest ever by a reigning MVP.[82]

In the 2016 playoffs, the Warriors defeated the Houston Rockets in the first round despite Curry only playing in the first half of Games 1 and 4 due to injury.[102][103][104] A right MCL injury kept him out of the first three games of the second round.[105] In Game 4 of the second-round series against the Portland Trail Blazers, Curry came off the bench to score 40 points in a 132–125 overtime win;[106] 17 of those points came in the extra period, an NBA record for points scored by an individual in overtime.[107] Curry led the Warriors to a 4–1 victory over the Trail Blazers, as they moved on to the Western Conference Finals to face the Oklahoma City Thunder. After going down 3–1, he helped the Warriors rally to win the series 4–3 and advance to their second straight NBA Finals.[108]

In the Finals, Curry's play relative to his regular season performance remained inconsistent, as it had been since he returned from injury against Portland;[109] still, he broke Danny Green's record of 27 three-pointers made in a Finals.[110] Despite being up 3–1 in the series, the Warriors were defeated by the Cleveland Cavaliers in seven games and became the first team in NBA Finals history to lose a series after leading 3–1. In the game seven loss, Curry scored 17 points on 6-of-19 shooting.[111]

Back-to-back championships (2016–2018)

On October 28, 2016, Curry hit four three-pointers against the New Orleans Pelicans to reach 1,600 for his career, becoming the 19th player to do so, as well as the fastest to reach the mark.[112] On November 4, Curry's NBA-record streak of 157 straight games with at least one made three-pointer was snapped during the Warriors' 117–97 loss to the Los Angeles Lakers after he went 0-of-10 from three-point range. He had hit a three-pointer in every regular-season game since November 11, 2014.[113] Three days later, he hit 13 three-pointers against New Orleans, setting an NBA record for most three-pointers made in a regular-season game. Curry shot 16-of-26 overall against the Pelicans for his first 40-point game of the season, finishing with 46 in a 116–106 win.[114] On December 11, Curry hit 2 three-pointers against the Minnesota Timberwolves to pass Steve Nash for 17th on the NBA's career three-pointers list.[115]

With 14 points against the Dallas Mavericks on December 30, Curry (11,903) passed Purvis Short (11,894) for seventh place on the Warriors' all-time scoring list.[116] In a loss to the Memphis Grizzlies on January 6, 2017, Curry had his second 40-point game of the season and reached the 12,000-point threshold, becoming the seventh player in Warriors history to score 12,000 career points.[117] On January 19, Curry was named a starter on the Western Conference All-Star team for the 2017 NBA All-Star Game.[118] On February 2, he hit his 200th three-pointer of the season in the Warriors' 133–120 win over the Los Angeles Clippers, making him the first player in NBA history to have 200 or more three-pointers in five consecutive seasons.[119] On March 5, he scored 31 points and moved into the top 10 on the NBA's career three-point list in a 112–105 win over the New York Knicks. Curry hit 5 three-pointers, passing Chauncey Billups for 10th place.[120]

Curry helped the Warriors sweep through the first two rounds of the playoffs.[121] In Game 1 of the Western Conference Finals against the San Antonio Spurs, Curry scored 40 points and hit a tying three-pointer with 1:48 remaining to help the Warriors rally from a 25-point deficit to win 113–111; the Warriors overcame their largest halftime deficit ever in the postseason at 20 points.[122] This was the second time in the season that the Warriors came back from a 20-point deficit against the Spurs.[123] In a 120–108 Game 3 win, Curry scored 21 points and became the franchise leader in postseason points, passing Rick Barry. They went up 3–0 in the series, becoming the third team in NBA history to win their first 11 playoff games.[124] His 36 points in Game 4 led to a 129–115 victory that saw the Warriors advance to the NBA Finals for a third straight year while becoming the first team in league history to start the playoffs 12–0.[125] In Game 2 of the 2017 NBA Finals against the Cleveland Cavaliers, Curry recorded his first career postseason triple-double with 32 points, 11 assists and 10 rebounds to help the Warriors go up 2–0 in the series with a 132–113 win.[126] Curry helped the Warriors clinch the series and the championship in Game 5 with 34 points, 10 assists, and six rebounds, as Golden State claimed its second title in three years.[127]


On July 1, 2017, Curry agreed to a five-year, $201 million extension with the Warriors, becoming the first NBA player to sign a supermax contract worth over $200 million.[128] He officially signed the contract on July 25.[129] On December 1, he scored 23 points and passed Jason Kidd for eighth place on the career three-pointers made list in a 133–112 win over the Orlando Magic.[130] On December 4, in a 125–115 win over the New Orleans Pelicans, Curry hit 5 three-pointers to become the fastest NBA player to achieve the milestone of 2,000 career three-pointers, achieving that mark in just 597 games, 227 less than the previous fastest player to achieve that mark, Ray Allen.[131][132] In that same game, Curry injured his right ankle and subsequently missed 11 games,[133] returning to action on December 30 and scoring 38 points with a season-high 10 three-pointers in a 141–128 win over the Memphis Grizzlies. Curry shot 13 for 17 and 10 of 13 from deep in 26 minutes for his ninth 30-point game of the season. It also marked Curry's ninth career game with 10 or more 3s, the most by any player in NBA history.[134]

On January 6, in a 121–105 win over the Los Angeles Clippers, Curry scored 45 points in three quarters.[135] On January 25, he scored 25 points in a 126–113 win over the Minnesota Timberwolves. Curry became the fifth player in Warriors history to score 14,000 points, ending the game with 14,023 and joining Wilt Chamberlain (17,783), Rick Barry (16,447), Paul Arizin (16,266), and Chris Mullin (16,235) on the franchise list.[136] On January 27, he scored 49 points—with 13 of those over the final 1:42—and hit 8 three-pointers, lifting the Warriors past the Boston Celtics 109–105.[137] On February 22, he had a 44-point effort with 8 three-pointers in a 134–127 win over the Los Angeles Clippers. It was his third 40-point game of the season.[138] On March 2, in a 114–109 win over the Atlanta Hawks, Curry made his 200th three-point field goal of the season, becoming the first player in NBA history with at least 200 three-pointers in six seasons, having reached the mark in every season since 2012–13.[139] Four days later, in a 114–101 win over the Nets, Curry became the seventh player in Warriors history to make 5,000 career field goals, joining Chamberlain, Barry, Mullin, Arizin, Jeff Mullins, and Nate Thurmond.[140]

On March 23, against the Hawks, Curry suffered a Grade 2 medial collateral ligament (MCL) sprain to his left knee.[141] He subsequently missed nearly six weeks, returning to action in Game 2 of the Warriors' second-round playoff series against the Pelicans. He came off the bench to score 28 points in a 121–116 win.[142] In Game 3 of the Western Conference Finals, Curry scored 35 points with 5 three-pointers in a 126–85 win over the Houston Rockets. The 41-point victory was the largest in franchise history during the postseason.[143] In Game 6, Curry scored 29 points with 5 three-pointers, as the Warriors rallied from an early 17-point deficit to stave off elimination with a 115–86 victory over the Rockets.[144] In Game 7, Curry recorded 27 points, 10 assists, and nine rebounds, as the Warriors earned a fourth straight trip to the NBA Finals by beating the Rockets 101–92.[145]

In Game 2 of the NBA Finals, Curry hit a Finals-record 9 three-pointers and scored 33 points in a 122–103 win over the Cavaliers.[146] In Game 4, Curry led all scorers with 37 points in a 108–85 win that helped the Warriors clinch their second straight championship with a series sweep over the Cavaliers.[147] Many felt that he should have won Finals MVP.[148] In response, Curry stated: "At the end of the day, I'm not going to let a [Finals] MVP trophy define my career. Three titles ... Wherever that puts us in the conversation in the history of the NBA ... I'm a three-time champ."[149] Rohan Nadkarni of Sports Illustrated argued that "the Golden State dynasty started with Stephen Curry. He, for numerous reasons stretching from his incredible talent to his previous ankle injuries, put the Warriors in place to win their third championship in four seasons."[150]

Fifth-straight NBA Finals (2018–2019)
On October 21, 2018, Curry had 30 points and 6 three-pointers in a 100–98 loss to the Denver Nuggets, thus moving past Paul Pierce for sixth place on the NBA's career three-point list.[151] Three days later, he scored 51 points with 11 three-pointers in only three quarters in a 144–122 win over the Washington Wizards. He scored 31 in the first half and finished with his sixth career 50-point game and made 10 or more 3s for the 10th time. Curry's third three-pointer of the night moved him past Jamal Crawford (2,153) for fifth place on the NBA's career three-point list.[152] On October 28, he made seven three-pointers and finished with 35 points in a 120–114 win over the Brooklyn Nets.[153] Over the first seven games of the season, he made at least 5 three-pointers in all seven games, breaking George McCloud's record of six games in a row during the 1995–96 season.[153] The Warriors started the season with a 10–1 record. On November 8 against the Milwaukee Bucks, Curry left the game during the third quarter with a groin injury[154] and the Warriors were unable to recover in a 134–111 loss.[155] Without Curry, the Warriors dropped to 12–7 on November 21 after enduring their first four-game losing streak since March 2013.[156] The Warriors ended November with a 15–8 record, with Curry's strained left groin sidelining him for 11 straight games.[157]

Despite Curry's 27 points in his return to the line-up on December 1, the Warriors were defeated 111–102 by the Detroit Pistons.[158] On December 17, he scored 20 points in a 110–93 win over the Memphis Grizzlies, becoming just the fifth player in Warriors history to score 15,000 points during the regular season, joining Wilt Chamberlain (17,783), Rick Barry (16,447), Paul Arizin (16,266), and Chris Mullin (16,235).[159] On December 23, he scored 42 points and made a layup with 0.5 seconds left to lift the Warriors to a 129–127 win over the Los Angeles Clippers.[160] On January 5, he had 10 three-pointers and scored 20 of his 42 points in the fourth quarter of the Warriors' 127–123 win over the Sacramento Kings.[161] On January 11, in a 146–109 win over the Chicago Bulls, Curry made 5 three-pointers to surpass Jason Terry (2,282) and move into third place all-time in NBA history behind Ray Allen (2,973) and Reggie Miller (2,560).[162] Two days later, he scored 48 points and hit a season high-tying 11 three-pointers in a 119–114 win over the Dallas Mavericks.[163] On January 16, he scored 41 points with 9 three-pointers to become the first player in NBA history to make eight or more 3s in three straight games, as the Warriors defeated the New Orleans Pelicans 147–140.[164] On January 31, he scored 41 points with 10 three-pointers in a 113–104 loss to the Philadelphia 76ers.[165] On February 21, he scored 36 points with 10 three-pointers in a 125–123 win over the Kings.[166] On March 16 against the Oklahoma City Thunder, Curry reached 16,000 career points.[167] On March 29, he made 11 three-pointers and scored 37 points in a 131–130 overtime loss to the Minnesota Timberwolves.[168] On April 2, in a 116–102 win over the Nuggets, Curry made 5 or more three-pointers in a career-best nine straight games and moved past Mullin for fourth place on the Warriors all-time points list.[169] On April 5, he scored 40 points in a 120–114 win over the Cleveland Cavaliers, thus moving past Arizin for third place on the Warriors all-time points list.[170]

The Warriors entered the playoffs as the first seed in the Western Conference with a 57–25 record. In Game 1 of the Warriors' first-round playoff series against the Clippers, Curry scored 38 points and made 8 three-pointers to give him the most in postseason history, passing Ray Allen (385). He also had a postseason career-high 15 rebounds and seven assists in a 121–104 win.[171] In Game 6 of the second round, Curry bounced back from the first scoreless first half of his playoff career to score 33 points in the last two quarters to help the Warriors eliminate the Houston Rockets with a 118–113 win and advance to the Western Conference Finals.[172] In Game 1 of the Conference Finals, Curry matched his postseason career high with 9 three-pointers to finish with 36 points in a 116–94 win over the Portland Trail Blazers.[173] Curry faced his brother Seth in that Finals series, making them the first set of brothers to face each other in an NBA playoff series.[174] Steph averaged a series career-high 36.5 points to help the Warriors sweep the Trail Blazers. It was the highest average by a player in a four-game sweep in NBA history.[175] Curry became the sixth player in NBA history to score 35 or more in the first four games of a series.[a] In Game 4, he had 37 points, 12 rebounds, and 11 assists in a 119–117 overtime win,[177] as he and Draymond Green became the first teammates in league history to have a triple-double in the same playoff game.[176] In Game 3 of the 2019 Finals, Curry scored a playoff career-high 47 points to go with eight rebounds and seven assists in a 123–109 loss to the Toronto Raptors.[178] In Game 5, he helped the Warriors stave off elimination with 31 points in a 106–105 win, cutting the Raptors' series lead to 3–2.[179] In Game 6, Curry scored 21 points, but shot just 6 for 17 and went 3 of 11 on three-pointers, including missing a contested three-pointer in the waning moments, as the Warriors lost the game and the series with a 114–110 defeat.[180]

Fourth NBA championship and first Finals MVP (2021–2022)

Curry during the 2022 NBA All-Star Game
On October 19, 2021, in the Warriors' season-opener, Curry recorded his eighth career triple-double with 21 points, 10 rebounds, and 10 assists in a 121–114 win against the Los Angeles Lakers.[198] On November 8, Curry scored 50 points, with 10 assists on nine three-pointers made, in a 127–113 win over the Atlanta Hawks.[199] It was the first time in Curry's career that he posted 50 points and 10 assists in the same game, as he unseated Chamberlain as the oldest player in history to put up that single-game line.[200] On November 12 against the Chicago Bulls, Curry became the NBA's career leader for three-pointers in both regular season and playoffs with 3,366, passing Ray Allen (3,358).[201] On December 14 at Madison Square Garden against the New York Knicks, Curry made his 2,974th career three-pointer to pass Ray Allen and become the NBA all-time leader in made three-pointers.[202] On January 21, 2022, Curry hit his first career buzzer-beating game-winner in a 105–103 win over the Houston Rockets, on a night where he put up 22 points and 12 assists.[203] On January 31, Curry scored 40 points, 21 of which in the fourth quarter, behind seven three-pointers and dished out nine assists to lead Golden State to a 122–108 victory over the Houston Rockets. His 21 fourth-quarter points were the highest of his career.[204]

In the 2022 NBA All-Star Game held on February 20, Curry's Team LeBron defeated Team Durant 163–160. Curry scored 50 points (just 2 points shy of the All-Star Game record set by Anthony Davis in 2017);[205] he also set the record for most three-pointers made in an All-Star quarter (6), half (8), and game (16),[206] and was named the All-Star Game MVP.[207] On February 24, Curry had a season-high 14 assists with 18 points in a 132–95 blowout win over the Portland Trail Blazers.[208] On March 10, Curry scored 34 points in a 113–102 win over the Denver Nuggets. He became the 49th player in NBA history to rack up 20,000 points.[209] On March 14, his 34th birthday, Curry scored 47 points in a 126–112 win over the Washington Wizards.[210] On March 16, in a 110–88 loss to the Boston Celtics, Curry suffered a sprained ligament in his left foot after having it rolled over by a diving Marcus Smart and was ruled out indefinitely.[211] On April 1, he was ruled out for the remainder of the regular season.[212]

On May 9, in Game 4 of the Western Conference semifinals against the Memphis Grizzlies, Curry became the first player in NBA history to make 500 career playoff threes.[213] During the Western Conference Finals against the Dallas Mavericks, he averaged 23.8 points, 6.6 rebounds and 7.4 assists per game. After the Warriors won the series in five games, Curry was named the unanimous and inaugural winner of the Western Conference Finals MVP award.[214] On June 10, in Game 4 of the NBA Finals, Curry logged 43 points, 10 rebounds, and four assists in a 107–97 victory over the Boston Celtics to even the series at 2–2. He became the first player in NBA history to make 5+ threes in four consecutive Finals games. Curry (at age 34 years, 88 days) also became the second-oldest player in NBA Finals history to record a 40-point, 10-rebound game behind only LeBron James in 2020 (at age 35 years, 284 days).[215] In Game 5 of the Finals, Curry passed Boston Celtics legend John Havlicek for 10th on the all-time Finals assists list.[216] In Game 6 of the Finals, Curry scored 34 points along with seven rebounds, seven assists, and led the Warriors to a 103–90 victory over the Celtics. He was named the NBA Finals MVP unanimously after averaging 31.2 points, 6.0 rebounds, 5.0 assists, and 2.0 steals per game.[217]
        """

OAKLAND_TEXT = """
Oakland is the largest city and the county seat of Alameda County, California, United States. A major West Coast port, Oakland is the largest city in the East Bay region of the San Francisco Bay Area, the third largest city overall in the Bay Area and the eighth most populated city in California. With a population of 440,646 in 2020,[13] it serves as the Bay Area's trade center and economic engine: the Port of Oakland is the busiest port in Northern California, and the fifth busiest in the United States of America.[18] The city was incorporated on May 4, 1852.[4] Oakland is a charter city.[19]

Oakland's territory covers what was once a mosaic of California coastal terrace prairie, oak woodland, and north coastal scrub.[20] In the late 18th century, it became part of a large rancho grant in the colony of New Spain. Its land served as a resource when its hillside oak and redwood timber were logged to build San Francisco.[20] The fertile flatland soils helped it become a prolific agricultural region. In the late 1860s, Oakland was selected as the western terminal of the Transcontinental Railroad.[21]

Following the catastrophic 1906 San Francisco earthquake, many San Francisco citizens moved to Oakland, enlarging the population, increasing its housing stock, and improving its infrastructure. It continued to grow in the 20th century with its busy port, shipyards, and a thriving automobile manufacturing industry. In the 21st century, Oakland suffered a disproportionate human toll from the Covid-pandemic within the San Francisco Bay Area, and between 2019 and 2023, Oakland became the first city in U.S. history to lose three professional major league sports teams to other cities within a span of five years: Oakland Raiders (NFL) went to Las Vegas; Golden State Warriors (NBA) to San Francisco; and Oakland Athletics (MLB), which is expected to relocate to Las Vegas.[22]
"""

class Documents:

    documents = []

    def __init__(self, paths=[]):
        self.documents = self.load_documents(paths)

    def load_documents(self, paths):
        pass

    def get_contents(self):
        return OAKLAND_TEXT